// SCRIPTS/generateTemplateMatrix.ts
// Phase14: Generate intent x persona template coverage matrix as Markdown,
// and also generate gaps (missing persona coverage) report.
//
// Usage (example):
//   npx ts-node SCRIPTS/generateTemplateMatrix.ts
//
// 前提:
// - NOTION_API_KEY
// - NOTION_DB_TUNING_TEMPLATES_ID
// が .env に設定されていること。

import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import type { NotionTuningTemplate } from "../src/integrations/notion/notionSchemas";
import { NotionSyncService } from "../src/integrations/notion/notionSyncService";

/**
 * Phase14: 公式ターゲット personaTag 一覧
 * - 現状のテンプレ + 将来拡張を見据えたタグ群
 */
const TARGET_PERSONA_TAGS: string[] = [
  "beginner",
  "business",
  "busy",
  "existing_user",
  "intermediate",
  "price_sensitive",
  "general",
];

/**
 * 1テンプレート x 1ペルソナごとに 1 行に展開した構造
 * （persona が空の場合は '(none)' を 1 行として扱う）
 */
type FlattenedTemplateRow = {
  phase: string;
  intent: string;
  personaTag: string;
  active: boolean;
  notionPageId: string;
  name: string;
};

/**
 * (phase, intent) ごとのギャップ情報
 */
type GapRow = {
  phase: string;
  intent: string;
  existingPersonaTags: string[];
  missingPersonaTags: string[];
};

/**
 * Notion から TuningTemplates を取得し、フラットな行配列に変換する
 */
async function fetchAndFlattenTemplates(): Promise<FlattenedTemplateRow[]> {
  const notionDbId = process.env.NOTION_DB_TUNING_TEMPLATES_ID;

  if (!notionDbId) {
    throw new Error("NOTION_DB_TUNING_TEMPLATES_ID is not set in environment");
  }

  const syncService = new NotionSyncService();
  const templates: NotionTuningTemplate[] =
    await syncService.syncTuningTemplates(notionDbId);

  const rows: FlattenedTemplateRow[] = [];

  for (const tpl of templates) {
    const phase = tpl.phase || "";
    const intent = tpl.intent ?? "";
    const personaList =
      tpl.persona && tpl.persona.length > 0 ? tpl.persona : ["(none)"];

    for (const personaTag of personaList) {
      rows.push({
        phase,
        intent,
        personaTag,
        active: tpl.active,
        notionPageId: tpl.notionPageId,
        name: tpl.name,
      });
    }
  }

  // phase, intent, personaTag の順でソート
  rows.sort((a, b) => {
    if (a.phase !== b.phase) return a.phase.localeCompare(b.phase);
    if (a.intent !== b.intent) return a.intent.localeCompare(b.intent);
    return a.personaTag.localeCompare(b.personaTag);
  });

  return rows;
}

/**
 * Markdown テーブル（フルマトリクス）を生成する
 */
function buildMatrixMarkdown(rows: FlattenedTemplateRow[]): string {
  const lines: string[] = [];

  lines.push("# Tuning Template Matrix");
  lines.push("");
  lines.push(
    "> This file is auto-generated by `SCRIPTS/generateTemplateMatrix.ts`."
  );
  lines.push("> Do not edit this file manually.");
  lines.push("");
  lines.push("| Phase | Intent | PersonaTag | Active | TemplateId | Name |");
  lines.push("|-------|--------|------------|--------|------------|------|");

  for (const row of rows) {
    const phase = row.phase || "-";
    const intent = row.intent || "-";
    const personaTag = row.personaTag || "(none)";
    const active = row.active ? "YES" : "NO";
    const templateId = row.notionPageId;
    const name = row.name.replace(/\|/g, "\\|");

    lines.push(
      `| ${phase} | ${intent} | ${personaTag} | ${active} | ${templateId} | ${name} |`
    );
  }

  lines.push("");
  return lines.join("\n");
}

/**
 * (phase, intent) ごとの不足 personaTag を集計する
 */
function computeGaps(rows: FlattenedTemplateRow[]): GapRow[] {
  // (phase,intent) -> Set(personaTag)
  const map = new Map<
    string,
    { phase: string; intent: string; personas: Set<string> }
  >();

  for (const row of rows) {
    const key = `${row.phase}::${row.intent}`;
    if (!map.has(key)) {
      map.set(key, {
        phase: row.phase,
        intent: row.intent,
        personas: new Set<string>(),
      });
    }

    // '(none)' は「ペルソナ未設定」扱いなのでギャップ判定には含めない
    if (row.personaTag && row.personaTag !== "(none)") {
      map.get(key)!.personas.add(row.personaTag);
    }
  }

  const gapRows: GapRow[] = [];

  for (const { phase, intent, personas } of map.values()) {
    // Clarify など intent 未設定のものはスキップしたければここで条件を入れてもよい
    const existing = Array.from(personas).sort();
    const missing = TARGET_PERSONA_TAGS.filter((tag) => !personas.has(tag));

    if (missing.length === 0) continue;

    gapRows.push({
      phase,
      intent,
      existingPersonaTags: existing,
      missingPersonaTags: missing,
    });
  }

  // 並びを固定
  gapRows.sort((a, b) => {
    if (a.phase !== b.phase) return a.phase.localeCompare(b.phase);
    return a.intent.localeCompare(b.intent);
  });

  return gapRows;
}

/**
 * 不足テンプレ一覧の Markdown を生成する
 */
function buildGapsMarkdown(gaps: GapRow[]): string {
  const lines: string[] = [];

  lines.push("# Tuning Template Gaps");
  lines.push("");
  lines.push("> Auto-generated by `SCRIPTS/generateTemplateMatrix.ts`.");
  lines.push("> Shows missing personaTag coverage for each (Phase, Intent).");
  lines.push("> Do not edit this file manually.");
  lines.push("");

  if (gaps.length === 0) {
    lines.push(
      "All target personaTags are covered for all (Phase, Intent). 🎉"
    );
    lines.push("");
    return lines.join("\n");
  }

  lines.push("| Phase | Intent | ExistingPersonaTags | MissingPersonaTags |");
  lines.push("|-------|--------|---------------------|--------------------|");

  for (const gap of gaps) {
    const existing =
      gap.existingPersonaTags.length > 0
        ? `[${gap.existingPersonaTags.map((t) => `"${t}"`).join(", ")}]`
        : "[]";
    const missing =
      gap.missingPersonaTags.length > 0
        ? `[${gap.missingPersonaTags.map((t) => `"${t}"`).join(", ")}]`
        : "[]";

    lines.push(
      `| ${gap.phase || "-"} | ${
        gap.intent || "-"
      } | ${existing} | ${missing} |`
    );
  }

  lines.push("");
  return lines.join("\n");
}

async function main() {
  try {
    const rows = await fetchAndFlattenTemplates();

    // 1) フルマトリクス出力
    const matrixMarkdown = buildMatrixMarkdown(rows);
    const matrixOutPath = path.join(
      __dirname,
      "..",
      "docs",
      "TEMPLATE_MATRIX.md"
    );
    fs.writeFileSync(matrixOutPath, matrixMarkdown, "utf8");

    // 2) ギャップ一覧出力
    const gaps = computeGaps(rows);
    const gapsMarkdown = buildGapsMarkdown(gaps);
    const gapsOutPath = path.join(__dirname, "..", "docs", "TEMPLATE_GAPS.md");
    fs.writeFileSync(gapsOutPath, gapsMarkdown, "utf8");

    // eslint-disable-next-line no-console
    console.log(
      `[generateTemplateMatrix] wrote ${rows.length} rows to ${matrixOutPath}`
    );
    // eslint-disable-next-line no-console
    console.log(
      `[generateTemplateMatrix] wrote ${gaps.length} gap rows to ${gapsOutPath}`
    );
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error("[generateTemplateMatrix] failed:", error);
    process.exit(1);
  }
}

if (require.main === module) {
  // 実行されたときのみ main() を呼び出す
  // （他のスクリプトから import された場合は実行しない）
  // eslint-disable-next-line @typescript-eslint/no-floating-promises
  main();
}
